/*
This file is automatically generated by https://github.com/oramtech/bootstrap-terraform-cloud

Modifications to this file may be lost the next time terraform is run on the
https://github.com/oramtech/bootstrap-terraform-cloud repo
*/

variable "dockertcp_host" { 
  type = string
}

variable "dockertcp_ca_material" { 
  type = string
}

variable "dockertcp_cert_material" { 
  type = string
}

variable "dockertcp_key_material" { 
  type = string
}


variable "cloudflare_account_id" {
  type = string
}

variable "cloudflare_api_token" {
  type = string
}

variable "cloudflare_dns_zone_id" {
  type = string
}

