/*
This file is automatically generated by https://github.com/oramtech/bootstrap-terraform-cloud

Modifications to this file may be lost the next time terraform is run on the
https://github.com/oramtech/bootstrap-terraform-cloud repo
*/

terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "2.24.0"
    }


  }

  cloud {
    organization = "oramtech"

    workspaces {
      name = "iac-watchtower"
    }
  }
}



provider "docker" {
  host     = var.dockertcp_host

  ca_material =  var.dockertcp_ca_material
  cert_material = var.dockertcp_cert_material
  key_material = var.dockertcp_key_material
}